### ISSUE TITLE
您好，我pip3 install torchtext

### ISSUE THREAD

**Issue by 17702513221** [sgalal/pinyin2hanzi#2]
libtorch_cpu.so: cannot open shared object file: No such file or directory

**Comment by sgalal** [comment]
可以试试先更新 torch 版本再安装 torchtext

另外我最近也在修改本项目代码，欢迎一起交流

**Comment by sgalal** [comment]
我重写了代码，现在不需要 torchtext 了。原来使用 torchtext 的部分改为手工处理的，所以现在不会有这个问题了。
